# DELETE http://localhost:8080/pokemon/release/100 # Content-Type: application/json # username: oryan

# { # "username" : "oryan" # }

POST http://localhost:3000/api/shorturl 
Content-Type: application/json 

{
    "url": "https://flexboxfroggy.com/",
    "username": "Oryan"
}

# POST http://localhost:3000/user/sign-up
# Content-Type: application/json 

# {
#     "name": "Oryan",
#     "email": "Oryan@gmail.com",
#     "password": "Oryan"
# }

# POST http://localhost:3000/user/login
# Content-Type: application/json 

# {
#     "email": "Oryan@gmail.com",
#     "password": "Oryan"
# }