# DELETE http://localhost:8080/pokemon/release/100 # Content-Type: application/json # username: oryan

# { # "username" : "oryan" # }

POST http://localhost:3000/api/shorturl 
Content-Type: application/json 

{
    "url": "https://flexboxfroggy.com/",
    "shortid": "12345",
    "username": "Moshe"
}

###

POST http://localhost:3000/user/sign-up
Content-Type: application/json 

{
    "name": "Moshe",
    "email": "Mos@gmail.com",
    "password": "oryan"
}

###

POST http://localhost:3000/user/login
Content-Type: application/json 

{
    "email": "Mos@gmail.com",
    "password": "oryan"
}

###

# GET http://localhost:3000/user/all-short-urls
# Content-Type: application/json 

# {
#     "username": "Oryan"
# }

###

GET http://localhost:3000/user/check
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTW9zaGUiLCJpYXQiOjE2MzcwNDc1NjksImV4cCI6MTYzNzA0NzYyOX0.ZR_gqvKrACa7ggUGYj99qC1JKX239HOwsKZP9rKCWig

