# DELETE http://localhost:8080/pokemon/release/100 # Content-Type: application/json # username: oryan

# { # "username" : "oryan" # }

# POST http://localhost:3000/api/shorturl 
# Content-Type: application/json 

# {
#     "url": "https://flexboxfroggy.com/",
#     "username": "Oryan"
# }

# POST http://localhost:3000/user/sign-up
# Content-Type: application/json 

# {
#     "name": "Moshe",
#     "email": "Moshe@gmail.com",
#     "password": "oryan"
# }

GET http://localhost:3000/user/all-short-urls
Content-Type: application/json 

{
    "username": "Oryan"
}